### ISSUE TITLE
Only works for people called Kane Cheshire

### ISSUE THREAD

**Issue by Jon889** [KaneCheshire/xcresultviewer#1]
The output file is hardcoded to `file:///Users/kanecheshire/xcresult.html` [here](https://github.com/KaneCheshire/xcresultviewer/blob/master/xcresult/ResultHandler.swift#L87) 😄 

It might be good to output it in the same directory as the xcresult and also use relative URLs for the images so the html/xcresult can be distributed or viewed from a remote CI.

**Comment by KaneCheshire** [comment]
Ooooops good catch! Pretty big oversight on my part in my haste to make it available lol! Thanks for raising. Will fix asap.

**Comment by KaneCheshire** [comment]
Okay I've just done a quick fix for now so it's not hardcoded to my user dir and then will look at addressing the other suggestions soon. Thanks again, and also sorry again. 🤦‍♂️

**Comment by Jon889** [comment]
ahah no problem, I can delete the /Users/kanecheshire directory now :)

**Comment by KaneCheshire** [comment]
Just updated to write the html data to the xcresult dir as well as use relative image paths ✅ thanks for your help :)
