### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftAppKit.dylib

### ISSUE THREAD

**Issue by bart-kneepkens** [KaneCheshire/xcresultviewer#5]

**Comment by shashankkrjain** [comment]
I am getting the same error. Can you help me out if you were able to solve it?

**Comment by KaneCheshire** [comment]
What does this have to do with xcresultviewer? xcresultviewer is a command line app?

**Comment by shashankkrjain** [comment]
I am running this command on a Mac CI server and getting this error:

```
bash-3.2$ ./xcrv
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/distiller/Library/Developer/Xcode/DerivedData/Synaptic-btcleycpnwfjuhdxkfbjjkegrnou/Logs/Test/./xcrv
  Reason: image not found
Abort trap: 6
```

**Comment by KaneCheshire** [comment]
Interesting, does it happen on your local machine? 

Also what version of macOS is your CI machine running?
