### ISSUE TITLE
Not able to install in Mac

### ISSUE THREAD

**Issue by kailashadhikari** [KaneCheshire/xcresultviewer#8]
Getting following error:
Fatal error: Missing path to xcresult: file /Users/kanecheshire/Projects/XCResultViewer/xcresult/XCResultViewer.swift, line 16
Illegal instruction: 4
@KaneCheshire can you suggest some documentation to configure in Mac

**Comment by KaneCheshire** [comment]
Please post the command you're running in Terminal here so I can help.

It looks to me like you haven't provided a path to an xcresult file.

**Comment by KaneCheshire** [comment]
As a reminder, the documentation [here](https://github.com/KaneCheshire/xcresultviewer#general-usage) says you have to provide a path to an xcresult: 

`./xcrv <options> '<path to an .xcresult bundle (usually located in derived data)>'`

**Comment by nagashreeabhilash100** [comment]
@KaneCheshire : This is the command using, but the webpage is not opened ./xcrv /Users/username/Library/Developer/Xcode/DerivedData/-filepath.xcresult

**Comment by KaneCheshire** [comment]
With that command do you still get `Fatal error: Missing path to xcresult`?

You should try wrapping the path in `'` as well, since spaces and other characters in the path might cause problems, like any Terminal command.

**Comment by nagashreeabhilash100** [comment]
Tried with '', still i am not able to see the report in web page. I am not seeing any error. 
This command ./xcrv  '/Users/username/Library/Developer/Xcode/DerivedData/-filepath.xcresult' does not throw any error, and does not opens any web page. Tried with other options of -s too, still no luck

**Comment by sachinvas** [comment]
@KaneCheshire This is not optimized for Xcode 11 `xcresult`. You need to use `xcresulttool` to get the structure as described https://help.apple.com/xcode/mac/current/#/devc38fc7392.

**Comment by KaneCheshire** [comment]
Ah I see, that makes sense. I’m not sure when I will get some time to look at this, in the meantime since it’s open source any contributions via PRs or sample code are encouraged.

**Comment by KaneCheshire** [comment]
That said, this is a different issue from the original issue, which was because no path to the xcresult bundle was provided. I’m going to close this issue, please open a new issue for other bugs and enhancements.
